model_config:
  conv_blocks: 4
  channels: [3,64,128,256,512]
  kernels: [7, 3, 3, 3]
  categories: 5
  fc_blocks: 1
  fc_dims: [512, 256]

data:
  chestexpert:
    traincsvpath: data/chestexpert/train.csv
    validcsvpath: data/chestexpert/valid.csv
    crossvalidcsvpath: data/chestexpert/cross_valid.csv
    imageroot: data/chestexpert

train_config:
  batchsize: 64
  warmup_steps: 200
  max_lr: 0.001
  min_lr: 0.00001
  epochs: 200